version: '3.8'
services:
  nn-assignment:
    build: .
    environment:
      - API_KEY=${OPENAI_API_KEY}
      - MODEL=${gpt-4:-google/flan-t5-small}
      - LOG_LEVEL=INFO
    volumes:
      - ./:/app
    restart: "no"
