apiVersion: v1
kind: ServiceAccount
metadata:
  name: person-finder
  namespace: person-finder
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: person-finder-role
  namespace: person-finder
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: person-finder-rolebinding
  namespace: person-finder
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: person-finder-role
subjects:
  - kind: ServiceAccount
    name: person-finder
    namespace: person-finder
