apiVersion: v1
kind: Service
metadata:
  name: person-finder
  namespace: person-finder
spec:
  selector:
    app: person-finder
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
